version: '3.8'

services:
  database:
    container_name: postgres
    image: postgres:11.2-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    depends_on:
#      - database
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_LISTEN_PORT: 5050
#    ports:
#      - "5050:5050"
